//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm.CommentService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CommentService.CommentServiceSoap")]
    public interface CommentServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddComment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AddComment(string productID, string username, string content, string star);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddComment", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AddCommentAsync(string productID, string username, string content, string star);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowCommentByProductId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ShowCommentByProductId(string productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowCommentByProductId", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ShowCommentByProductIdAsync(string productID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CommentServiceSoapChannel : WebForm.CommentService.CommentServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommentServiceSoapClient : System.ServiceModel.ClientBase<WebForm.CommentService.CommentServiceSoap>, WebForm.CommentService.CommentServiceSoap {
        
        public CommentServiceSoapClient() {
        }
        
        public CommentServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommentServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommentServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommentServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddComment(string productID, string username, string content, string star) {
            return base.Channel.AddComment(productID, username, content, star);
        }
        
        public System.Threading.Tasks.Task<bool> AddCommentAsync(string productID, string username, string content, string star) {
            return base.Channel.AddCommentAsync(productID, username, content, star);
        }
        
        public System.Data.DataTable ShowCommentByProductId(string productID) {
            return base.Channel.ShowCommentByProductId(productID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ShowCommentByProductIdAsync(string productID) {
            return base.Channel.ShowCommentByProductIdAsync(productID);
        }
    }
}
